# 定义 stages
stages:
  - lint
  - code_scan
  - build
  - functional_tests
  - integration_tests

# 定义参数
variables:
  # build文件夹
  BUILD_PATH: build
  # 需要发送的安全依赖文件，java语言则对应为pom.xml，python语言则为requirements.txt，nodejs语言则为package.json,go语言则为go.sum，php语言则为composer.lock
  # 注意java项目管理如使用gradle，发送依赖文件为父节点下包含依赖版本的thirdparty.gradle文件
  # 依赖文件在项目根目录则填写依赖文件名称即可，若项目不在根目录，则需要加上相对路径
  DEPEND_FILE: CMakeLists.txt
  # 该仓库开发语言类型。 选项： java,python,nodejs,go,php,gradle
  LANGUAGE: c++
  FS_HOST: 'http://jssz-inner-boss.bilibili.co'
  ACCESS_KEY_ID: '7df5c4dc25027e7e'
  SECRET_ACCESS_KEY: 'b1366ca38d65975a1f7f37628fce511b'
  BUCKET: datacenter-alter
  LOCAL_CK_PATH: /mnt/storage00/ck_package_ci_25/clickhouse

include:
  - project: 'xuneng/datacenter-ci-script'
    ref: master
    file: 'security/lint_depend_scan.yml'

# 代码检查
code_scan:
  stage: code_scan
  resource_group: devide
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev-25"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^release\/25\.5.*$/'
    - when: never
  script:
    - echo "code_scan begin"
    # - docker run --rm --privileged --ulimit memlock=-1:-1 -v $(pwd):/clickhouse -w /clickhouse ci_code_scan:v1 bash bili_ci/code_scan.sh
    - echo "code_scan end"

# 构建
build:
  stage: build
  resource_group: devide
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev-25"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^release\/25\.5.*$/'
    - when: never
  before_script:
    - echo "exec git before_script"
    - echo "git branch bef name " $CI_COMMIT_REF_NAME
    - echo "git branch commit sha " $CI_COMMIT_SHA
    - GITLAB_RUNNER_PATH=`pwd`
    - echo "gitlab runner path " $GITLAB_RUNNER_PATH
    - echo "change to local ck path " $LOCAL_CK_PATH
    - cd $LOCAL_CK_PATH
    - git fetch origin $CI_COMMIT_SHA
    - git checkout $CI_COMMIT_SHA
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - echo "check local build dir is exist"
    - if [[ ! -d "$BUILD_PATH" ]]; then echo "build dir is not exist" && mkdir -p $BUILD_PATH; else echo "build dir is exist" && rm -rf $BUILD_PATH/*; fi
    - echo "build begin"
    - docker run --rm -v $LOCAL_CK_PATH:/clickhouse -w /clickhouse build_dev_25:v1 bash bili_ci/ci_build.sh
    - echo "build end"
  script:
    - echo "cp local file to gitlab"
    - cd $GITLAB_RUNNER_PATH
    - echo "check gitlab build dir is exist"
    - mkdir -p build/programs && rm -rf build/programs/*
    - cp $LOCAL_CK_PATH/build/programs/clickhouse build/programs/
  artifacts:
    paths:
      - ./build/programs/clickhouse
    expire_in: 1 day

# 功能测试
functional_tests:
  resource_group: devide
  stage: functional_tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev-25"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^release\/25\.5.*$/'
    - when: never
  script:
    - echo "functional_tests begin"
    - docker run --rm --privileged --ulimit memlock=-1:-1 -v $(pwd)/bili_ci/config/func_test/config.xml:/etc/clickhouse-server/config.xml -v $(pwd)/bili_ci/config/func_test/users.xml:/etc/clickhouse-server/users.xml -v $(pwd):/clickhouse -w /clickhouse ci_dev_25:v1 bash bili_ci/ci_function_test.sh
    - echo "functional_tests end"
  dependencies:
    - build

# 集成测试
integration_tests:
  resource_group: devide
  stage: integration_tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev-25"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^release\/25\.5.*$/'
    - when: never
  script:
    - echo "integration_tests begin"
    - ./tests/integration/runner --binary $BUILD_PATH/programs/clickhouse --base-configs-dir bili_ci/config/inter_test --docker-image-version v25 test_ddl_alter_query test_distributed_ddl test_system_merges test_zookeeper_config test_cluster_all_replicas test_replicated_merge_tree_config test_consistant_parts_after_move_partition test_multiple_disks test_rename_column test_ttl_move test_repliacted_storage_unique_engine test_replicated_bsi
    - echo "integration_tests end"
  dependencies:
    - build
